apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicasetname
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mycontainername
        image: nginx
